### ISSUE TITLE
How about an interactive HTML/Javascript desktop

### ISSUE THREAD

**Issue by tisaconundrum2** [TheCyaniteProject/exit_code_java#1]
Use HTML/Javascript to replicate an interactive desktop.
Refer to [this repository](https://github.com/tisaconundrum2/pspwxp)

**Comment by TheCyaniteProject** [comment]
Firstly, you look like that one guy from TeamEdge. x3

Secondly, I would like to further discuss this topic. Preferably on Telegram(@TheCyaniteProject) but I can do Twitter(@exit_code_dev).
