### ISSUE TITLE
Console interpreter should really be a static class?

### ISSUE THREAD

**Issue by tiagoanleite** [TheCyaniteProject/exit_code_java#5]
I was browsing through the projects code and one thing that stood out to me was the fact that the console interpreter was a static class.

Since the game emulates a real OS that can have several Terminal instances open at the same time shouldn't each Terminal window be able to create its own instance of the command interpreter?

That not only matches more closely a real OS but also gives you a lot more flexibility regarding adding more features to your commands.

**Comment by JuliusFreudenberger** [comment]
We were and are working on the terminal and commands and kept your idea in our minds and I think we found a quite good solution for an instance of console for every terminal app.
