### ISSUE TITLE
Project structure explanation?

### ISSUE THREAD

**Issue by thegamblerrises** [TheCyaniteProject/exit_code_java#6]
Hi, Could you please let me know project structure? To run it in IDE, I have to re-organize it. Can I restructure it with any build-tool? Thanks

**Comment by SitiSchu** [comment]
All files are in `main/src/` in the dev branch,

**Comment by thegamblerrises** [comment]
Ok, I got confused with `main/application` folder, since it has almost same files.

Also, project structure is not as per 'java way', so IDEs are not recognizing it. If we reorganize it, it will be better and easier to run.
